name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check commit messages
      uses: wagoid/commitlint-github-action@v5

    - name: Lint code
      run: npm run lint

    - name: Type check
      run: npm run type-check

    - name: Run unit tests
      run: npm run test:ci

    - name: Upload test coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage/

  e2e:
    name: E2E Tests
    runs-on: macos-latest
    needs: validate
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Detox CLI
      run: npm install -g detox-cli

    - name: Build app for testing
      run: npm run build:e2e

    - name: Run E2E tests
      run: npm run test:e2e

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: e2e-artifacts
        path: artifacts/

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit
      run: npm audit

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build production bundle
      run: npm run build:prod

    - name: Analyze bundle size
      run: |
        npx bundlesize --files "dist/**/*.js" --max-size 500kb
      continue-on-error: true

  accessibility:
    name: Accessibility Check
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run accessibility tests
      run: npm run test:a11y

  documentation:
    name: Documentation Check
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check documentation coverage
      run: npm run docs:coverage

    - name: Validate documentation links
      run: npm run docs:validate

  notify:
    name: Notify on Completion
    runs-on: ubuntu-latest
    needs: [validate, e2e, security, bundle-analysis, accessibility, documentation]
    if: always()
    
    steps:
    - name: Check job status
      id: check
      run: |
        if [[ "${{ needs.validate.result }}" == "success" && \
              "${{ needs.e2e.result }}" == "success" && \
              "${{ needs.security.result }}" == "success" && \
              "${{ needs.bundle-analysis.result }}" == "success" && \
              "${{ needs.accessibility.result }}" == "success" && \
              "${{ needs.documentation.result }}" == "success" ]]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
        fi

    - name: Create status check
      uses: actions/github-script@v6
      with:
        script: |
          const status = "${{ steps.check.outputs.status }}"
          const description = status === "success" 
            ? "All checks passed successfully" 
            : "Some checks failed"
          
          await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'PR Validation',
            head_sha: context.sha,
            status: 'completed',
            conclusion: status,
            output: {
              title: status === "success" ? "PR Validation Passed" : "PR Validation Failed",
              summary: description
            }
          })
